-- =====================================================================
--  Medikz · Migración 007 · Catálogo de medicamentos
-- =====================================================================
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS medicamentos (
    id             INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    nombre         VARCHAR(200)  NOT NULL,
    concentracion  VARCHAR(80)   DEFAULT NULL,
    presentacion   VARCHAR(80)   DEFAULT NULL,
    categoria      VARCHAR(60)   DEFAULT NULL,
    activo         TINYINT(1)    NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    FULLTEXT KEY ft_med_nombre (nombre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO medicamentos (nombre, concentracion, presentacion, categoria) VALUES
-- Antibióticos
('Amoxicilina', '500mg', 'Cápsulas', 'Antibiótico'),
('Amoxicilina', '250mg/5ml', 'Suspensión', 'Antibiótico'),
('Amoxicilina / Ácido Clavulánico', '875/125mg', 'Tabletas', 'Antibiótico'),
('Azitromicina', '500mg', 'Tabletas', 'Antibiótico'),
('Azitromicina', '200mg/5ml', 'Suspensión', 'Antibiótico'),
('Claritromicina', '500mg', 'Tabletas', 'Antibiótico'),
('Ciprofloxacino', '500mg', 'Tabletas', 'Antibiótico'),
('Ciprofloxacino', '250mg', 'Tabletas', 'Antibiótico'),
('Levofloxacino', '500mg', 'Tabletas', 'Antibiótico'),
('Metronidazol', '500mg', 'Tabletas', 'Antibiótico'),
('Metronidazol', '250mg/5ml', 'Suspensión', 'Antibiótico'),
('Trimetoprim / Sulfametoxazol', '160/800mg', 'Tabletas', 'Antibiótico'),
('Cefalexina', '500mg', 'Cápsulas', 'Antibiótico'),
('Cefalexina', '250mg/5ml', 'Suspensión', 'Antibiótico'),
('Cefixima', '400mg', 'Tabletas', 'Antibiótico'),
('Cefixima', '100mg/5ml', 'Suspensión', 'Antibiótico'),
('Doxiciclina', '100mg', 'Cápsulas', 'Antibiótico'),
('Nitrofurantoína', '100mg', 'Cápsulas', 'Antibiótico'),
('Clindamicina', '300mg', 'Cápsulas', 'Antibiótico'),
('Dicloxacilina', '500mg', 'Cápsulas', 'Antibiótico'),
-- Analgésicos / Antiinflamatorios
('Paracetamol', '500mg', 'Tabletas', 'Analgésico'),
('Paracetamol', '1g', 'Tabletas', 'Analgésico'),
('Paracetamol', '150mg/5ml', 'Suspensión pediátrica', 'Analgésico'),
('Ibuprofeno', '400mg', 'Tabletas', 'Antiinflamatorio'),
('Ibuprofeno', '600mg', 'Tabletas', 'Antiinflamatorio'),
('Ibuprofeno', '100mg/5ml', 'Suspensión', 'Antiinflamatorio'),
('Naproxeno', '250mg', 'Tabletas', 'Antiinflamatorio'),
('Naproxeno', '500mg', 'Tabletas', 'Antiinflamatorio'),
('Diclofenaco', '50mg', 'Tabletas', 'Antiinflamatorio'),
('Diclofenaco', '75mg/3ml', 'Solución inyectable', 'Antiinflamatorio'),
('Ketorolaco', '10mg', 'Tabletas', 'Analgésico'),
('Ketorolaco', '30mg/1ml', 'Solución inyectable', 'Analgésico'),
('Meloxicam', '7.5mg', 'Tabletas', 'Antiinflamatorio'),
('Meloxicam', '15mg', 'Tabletas', 'Antiinflamatorio'),
('Celecoxib', '200mg', 'Cápsulas', 'Antiinflamatorio'),
('Metamizol (Dipirona)', '500mg', 'Tabletas', 'Analgésico'),
('Metamizol (Dipirona)', '500mg/ml', 'Solución inyectable', 'Analgésico'),
('Tramadol', '50mg', 'Cápsulas', 'Analgésico'),
('Tramadol', '100mg', 'Tabletas liberación prolongada', 'Analgésico'),
-- Antihistamínicos
('Loratadina', '10mg', 'Tabletas', 'Antihistamínico'),
('Loratadina', '5mg/5ml', 'Jarabe', 'Antihistamínico'),
('Cetirizina', '10mg', 'Tabletas', 'Antihistamínico'),
('Cetirizina', '5mg/5ml', 'Jarabe', 'Antihistamínico'),
('Fexofenadina', '120mg', 'Tabletas', 'Antihistamínico'),
('Fexofenadina', '180mg', 'Tabletas', 'Antihistamínico'),
('Difenhidramina', '25mg', 'Tabletas', 'Antihistamínico'),
('Clorfeniramina', '4mg', 'Tabletas', 'Antihistamínico'),
('Levocetirizina', '5mg', 'Tabletas', 'Antihistamínico'),
('Desloratadina', '5mg', 'Tabletas', 'Antihistamínico'),
-- Gastrointestinales
('Omeprazol', '20mg', 'Cápsulas', 'Gastrointestinal'),
('Omeprazol', '40mg', 'Cápsulas', 'Gastrointestinal'),
('Lansoprazol', '30mg', 'Cápsulas', 'Gastrointestinal'),
('Pantoprazol', '40mg', 'Tabletas', 'Gastrointestinal'),
('Esomeprazol', '40mg', 'Cápsulas', 'Gastrointestinal'),
('Metoclopramida', '10mg', 'Tabletas', 'Gastrointestinal'),
('Metoclopramida', '5mg/5ml', 'Jarabe', 'Gastrointestinal'),
('Domperidona', '10mg', 'Tabletas', 'Gastrointestinal'),
('Ondansetrón', '4mg', 'Tabletas', 'Gastrointestinal'),
('Ondansetrón', '8mg', 'Tabletas', 'Gastrointestinal'),
('Loperamida', '2mg', 'Cápsulas', 'Gastrointestinal'),
('Simeticona', '80mg', 'Tabletas masticables', 'Gastrointestinal'),
('Subsalicilato de bismuto', '262mg', 'Tabletas masticables', 'Gastrointestinal'),
('Ranitidina', '150mg', 'Tabletas', 'Gastrointestinal'),
('Sales de rehidratación oral', NULL, 'Sobre', 'Gastrointestinal'),
-- Cardiovasculares
('Enalapril', '5mg', 'Tabletas', 'Cardiovascular'),
('Enalapril', '10mg', 'Tabletas', 'Cardiovascular'),
('Enalapril', '20mg', 'Tabletas', 'Cardiovascular'),
('Losartán', '25mg', 'Tabletas', 'Cardiovascular'),
('Losartán', '50mg', 'Tabletas', 'Cardiovascular'),
('Losartán', '100mg', 'Tabletas', 'Cardiovascular'),
('Amlodipino', '5mg', 'Tabletas', 'Cardiovascular'),
('Amlodipino', '10mg', 'Tabletas', 'Cardiovascular'),
('Metoprolol', '25mg', 'Tabletas', 'Cardiovascular'),
('Metoprolol', '50mg', 'Tabletas', 'Cardiovascular'),
('Metoprolol', '100mg', 'Tabletas', 'Cardiovascular'),
('Atenolol', '50mg', 'Tabletas', 'Cardiovascular'),
('Atenolol', '100mg', 'Tabletas', 'Cardiovascular'),
('Lisinopril', '5mg', 'Tabletas', 'Cardiovascular'),
('Lisinopril', '10mg', 'Tabletas', 'Cardiovascular'),
('Lisinopril', '20mg', 'Tabletas', 'Cardiovascular'),
('Hidroclorotiazida', '25mg', 'Tabletas', 'Cardiovascular'),
('Furosemida', '40mg', 'Tabletas', 'Cardiovascular'),
('Espironolactona', '25mg', 'Tabletas', 'Cardiovascular'),
('Carvedilol', '6.25mg', 'Tabletas', 'Cardiovascular'),
('Carvedilol', '12.5mg', 'Tabletas', 'Cardiovascular'),
('Carvedilol', '25mg', 'Tabletas', 'Cardiovascular'),
('Nifedipino', '30mg', 'Tabletas liberación prolongada', 'Cardiovascular'),
('Verapamilo', '80mg', 'Tabletas', 'Cardiovascular'),
('Digoxina', '0.25mg', 'Tabletas', 'Cardiovascular'),
('Warfarina', '5mg', 'Tabletas', 'Cardiovascular'),
('Ácido acetilsalicílico', '100mg', 'Tabletas', 'Cardiovascular'),
('Clopidogrel', '75mg', 'Tabletas', 'Cardiovascular'),
('Nitroglicerina', '0.4mg/dosis', 'Spray sublingual', 'Cardiovascular'),
-- Diabetes
('Metformina', '500mg', 'Tabletas', 'Antidiabético'),
('Metformina', '850mg', 'Tabletas', 'Antidiabético'),
('Metformina', '1000mg', 'Tabletas', 'Antidiabético'),
('Glibenclamida', '5mg', 'Tabletas', 'Antidiabético'),
('Glipizida', '5mg', 'Tabletas', 'Antidiabético'),
('Sitagliptina', '100mg', 'Tabletas', 'Antidiabético'),
('Empagliflozina', '10mg', 'Tabletas', 'Antidiabético'),
('Empagliflozina', '25mg', 'Tabletas', 'Antidiabético'),
('Dapagliflozina', '10mg', 'Tabletas', 'Antidiabético'),
('Insulina NPH', '100 UI/ml', 'Solución inyectable', 'Antidiabético'),
('Insulina Regular', '100 UI/ml', 'Solución inyectable', 'Antidiabético'),
('Insulina Glargina', '100 UI/ml', 'Solución inyectable', 'Antidiabético'),
-- Lípidos
('Atorvastatina', '10mg', 'Tabletas', 'Hipolipemiante'),
('Atorvastatina', '20mg', 'Tabletas', 'Hipolipemiante'),
('Atorvastatina', '40mg', 'Tabletas', 'Hipolipemiante'),
('Atorvastatina', '80mg', 'Tabletas', 'Hipolipemiante'),
('Rosuvastatina', '10mg', 'Tabletas', 'Hipolipemiante'),
('Rosuvastatina', '20mg', 'Tabletas', 'Hipolipemiante'),
('Simvastatina', '20mg', 'Tabletas', 'Hipolipemiante'),
('Simvastatina', '40mg', 'Tabletas', 'Hipolipemiante'),
('Gemfibrozilo', '600mg', 'Tabletas', 'Hipolipemiante'),
('Fenofibrato', '160mg', 'Cápsulas', 'Hipolipemiante'),
('Ezetimiba', '10mg', 'Tabletas', 'Hipolipemiante'),
-- Respiratorios
('Salbutamol', '100mcg/dosis', 'Inhalador', 'Broncodilatador'),
('Salbutamol', '2mg/5ml', 'Jarabe', 'Broncodilatador'),
('Budesonida', '200mcg/dosis', 'Inhalador', 'Corticoide inhalado'),
('Fluticasona', '50mcg/dosis', 'Inhalador', 'Corticoide inhalado'),
('Fluticasona', '125mcg/dosis', 'Inhalador', 'Corticoide inhalado'),
('Montelukast', '10mg', 'Tabletas', 'Broncodilatador'),
('Montelukast', '4mg', 'Gránulos pediátricos', 'Broncodilatador'),
('Beclometasona', '50mcg/dosis', 'Inhalador', 'Corticoide inhalado'),
('Ipratropio', '20mcg/dosis', 'Inhalador', 'Broncodilatador'),
('Ambroxol', '30mg/5ml', 'Jarabe', 'Expectorante'),
('Acetilcisteína', '600mg', 'Tabletas efervescentes', 'Mucolítico'),
('Dextrometorfano', '15mg/5ml', 'Jarabe', 'Antitusivo'),
-- Vitaminas / Suplementos
('Ácido fólico', '400mcg', 'Tabletas', 'Vitamina'),
('Ácido fólico', '5mg', 'Tabletas', 'Vitamina'),
('Sulfato ferroso', '325mg', 'Tabletas', 'Suplemento'),
('Vitamina C', '500mg', 'Tabletas', 'Vitamina'),
('Vitamina C', '1000mg', 'Tabletas efervescentes', 'Vitamina'),
('Vitamina D3', '1000 UI', 'Cápsulas', 'Vitamina'),
('Vitamina D3', '2000 UI', 'Cápsulas', 'Vitamina'),
('Calcio + Vitamina D3', '500mg/200 UI', 'Tabletas', 'Suplemento'),
('Complejo B', NULL, 'Tabletas', 'Vitamina'),
('Zinc', '20mg', 'Tabletas', 'Suplemento'),
('Omega 3', '1000mg', 'Cápsulas blandas', 'Suplemento'),
('Magnesio', '400mg', 'Tabletas', 'Suplemento'),
-- Neurológico / Psiquiátrico
('Diazepam', '5mg', 'Tabletas', 'Ansiolítico'),
('Diazepam', '10mg', 'Tabletas', 'Ansiolítico'),
('Alprazolam', '0.25mg', 'Tabletas', 'Ansiolítico'),
('Alprazolam', '0.5mg', 'Tabletas', 'Ansiolítico'),
('Alprazolam', '1mg', 'Tabletas', 'Ansiolítico'),
('Clonazepam', '0.5mg', 'Tabletas', 'Antiepiléptico'),
('Clonazepam', '2mg', 'Tabletas', 'Antiepiléptico'),
('Sertralina', '50mg', 'Tabletas', 'Antidepresivo'),
('Sertralina', '100mg', 'Tabletas', 'Antidepresivo'),
('Fluoxetina', '20mg', 'Cápsulas', 'Antidepresivo'),
('Escitalopram', '10mg', 'Tabletas', 'Antidepresivo'),
('Escitalopram', '20mg', 'Tabletas', 'Antidepresivo'),
('Amitriptilina', '25mg', 'Tabletas', 'Antidepresivo'),
('Carbamazepina', '200mg', 'Tabletas', 'Antiepiléptico'),
('Ácido valproico', '500mg', 'Tabletas', 'Antiepiléptico'),
('Pregabalina', '75mg', 'Cápsulas', 'Antiepiléptico'),
('Pregabalina', '150mg', 'Cápsulas', 'Antiepiléptico'),
('Gabapentina', '300mg', 'Cápsulas', 'Antiepiléptico'),
('Quetiapina', '25mg', 'Tabletas', 'Antipsicótico'),
('Zolpidem', '10mg', 'Tabletas', 'Hipnótico'),
-- Hormonales / Tiroides
('Levotiroxina', '50mcg', 'Tabletas', 'Hormona tiroidea'),
('Levotiroxina', '100mcg', 'Tabletas', 'Hormona tiroidea'),
('Levotiroxina', '150mcg', 'Tabletas', 'Hormona tiroidea'),
('Progesterona', '100mg', 'Cápsulas', 'Hormona'),
('Progesterona', '200mg', 'Cápsulas', 'Hormona'),
('Medroxiprogesterona', '150mg/ml', 'Suspensión inyectable', 'Anticonceptivo'),
('Anticonceptivo oral combinado (Levonorgestrel + Etinilestradiol)', '0.15/0.03mg', 'Tabletas', 'Anticonceptivo'),
-- Corticosteroides
('Prednisona', '5mg', 'Tabletas', 'Corticoide'),
('Prednisona', '20mg', 'Tabletas', 'Corticoide'),
('Prednisona', '50mg', 'Tabletas', 'Corticoide'),
('Dexametasona', '0.5mg', 'Tabletas', 'Corticoide'),
('Dexametasona', '4mg/ml', 'Solución inyectable', 'Corticoide'),
('Betametasona', '0.5mg', 'Tabletas', 'Corticoide'),
('Metilprednisolona', '4mg', 'Tabletas', 'Corticoide'),
('Metilprednisolona', '500mg/vial', 'Polvo inyectable', 'Corticoide'),
-- Antiparasitarios
('Albendazol', '200mg', 'Tabletas masticables', 'Antiparasitario'),
('Albendazol', '400mg', 'Tabletas', 'Antiparasitario'),
('Ivermectina', '3mg', 'Tabletas', 'Antiparasitario'),
('Ivermectina', '6mg', 'Tabletas', 'Antiparasitario'),
('Mebendazol', '100mg', 'Tabletas masticables', 'Antiparasitario'),
-- Dermatológicos tópicos
('Clotrimazol', '1%', 'Crema tópica', 'Antifúngico'),
('Miconazol', '2%', 'Crema tópica', 'Antifúngico'),
('Terbinafina', '1%', 'Crema tópica', 'Antifúngico'),
('Mupirocina', '2%', 'Ungüento tópico', 'Antibiótico tópico'),
('Hidrocortisona', '1%', 'Crema tópica', 'Corticoide tópico'),
('Betametasona', '0.05%', 'Crema tópica', 'Corticoide tópico'),
('Mometasona', '0.1%', 'Crema tópica', 'Corticoide tópico'),
('Tretinoína', '0.025%', 'Crema tópica', 'Dermatológico'),
('Tretinoína', '0.05%', 'Crema tópica', 'Dermatológico'),
('Aciclovir', '5%', 'Crema tópica', 'Antiviral tópico');
